version: "2"
services:
  weba:
    build: .
    volumes:
      - ./:/app
    expose:
      - 80
    links:
      - mongo
  webb:
    build: .
    volumes:
      - ./:/app
    expose:
      - 80
    links:
      - mongo
  webc:
    build: .
    volumes:
      - ./:/app
    expose:
      - 80
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27018:27017"
  haproxy:
    image: haproxy:latest
    build: ./haproxy
    links:
     - weba
     - webb
     - webc
    ports:
     - "80:80"
     - "70:70"

    expose:
     - "80"
     - "70"
