version: "2"
services:
  weba:
    build: .
    volumes:
      - ./:/app
    expose:
      - 80
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    # ports:
    #   - "80:80"
  webb:
    build: .
    volumes:
      - ./:/app
    expose:
      - 80
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
  webc:
    build: .
    volumes:
      - ./:/app
    expose:
      - 80
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
  scheduler:
    build:
      context: .
      dockerfile: ./dockerBuilds/scheduler/Dockerfile
    volumes:
      - ./:/app
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"
  haproxy:
    image: haproxy:latest
    build: ./dockerBuilds/haproxy
    links:
     - weba
     - webb
     - webc
    ports:
     - "443:443" 
     - "80:80"
     - "70:70"
    expose:
     - "80"
     - "70"
     - "443"
