version: "2"
services:
  weba:
    build: .
    volumes:
      - ./:/app
    expose:
      - 80
    links:
      - mongo
      - memcached
  webb:
    build: .
    volumes:
      - ./:/app
    expose:
      - 80
    links:
      - mongo
      - memcached
  webc:
    build: .
    volumes:
      - ./:/app
    expose:
      - 80
    links:
      - mongo
      - memcached
  scheduler:
    build:
      context: .
      dockerfile: ./dockerBuilds/scheduler/Dockerfile
    volumes:
      - ./:/app
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27018:27017"
  memcached:
    image: sameersbn/memcached:latest
    ports:
      - "11211:11211"
    restart: always
  haproxy:
    image: haproxy:latest
    build: ./dockerBuilds/haproxy
    links:
     - weba
     - webb
     - webc
    ports:
     - "80:80"
     - "70:70"

    expose:
     - "80"
     - "70"
