version: "2"
services:
  weba:
    build: .
    volumes:
      - ./:/usr/src/app
    expose:
      - 80
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    # ports:
    #   - "80:80"
  webb:
    build: .
    volumes:
      - ./:/usr/src/app
    expose:
      - 80
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
  webc:
    build: .
    volumes:
      - ./:/usr/src/app
    expose:
      - 80
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
  scheduler:
    build: 
      context: .
      dockerfile: ./dockerBuilds/scheduler/Dockerfile
    volumes:
      - ./:/usr/src/app
    links:
      - redis
    depends_on:
      - redis
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"
  # Comment this section (eg: 'nginx-proxy') to run server locally without nginx proxying to vhost + 'ports'
  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #   expose:
  #     - "80"
  haproxy:
    image: haproxy:latest
    build: ./dockerBuilds/haproxy
    links:
     - weba
     - webb
     - webc
    # Uncomment this section (eg: 'ports') to run server locally without nginx proxying to vhost
    ports:
     - "443:443" 
     - "80:80"
     - "70:70"
    expose:
     - "80"
     - "70"
     - "443"
    # environment:
    #  - VIRTUAL_HOST=bestway.clementpeyrabere.net
    #  - VIRTUAL_PORT=443
