FROM haproxy:latest
COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
COPY bestway.clementpeyrabere.net.pem /etc/ssl/bestway/bestway.clementpeyrabere.net.pem
RUN ls /etc/ssl/bestway/bestway.clementpeyrabere.net.pem
